// Ein DAISY Hörbuch bestellen
OPTIONS {{host}}/{{api-version}}/bestellung/{{titelnummer}}
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

###

// Ein DAISY Hörbuch bestellen
POST {{host}}/{{api-version}}/bestellung/{{titelnummer}}
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}
Content-Type: application/json

> {%
client.global.set("orderId", response.json.orderId);
%}

###

//  Den Status einer Bestellung eines DAISY Hörbuchs abfragen
OPTIONS {{host}}/{{api-version}}/bestellung/{{titelnummer}}/status/{{orderId}}
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

###

//  Den Status einer Bestellung eines DAISY Hörbuchs abfragen
GET {{host}}/{{api-version}}/bestellung/{{titelnummer}}/status/{{orderId}}
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

###

//  Eine zuvor bestelltes DAISY Hörbuch abrufen
GET {{host}}/{{api-version}}/bestellung/{{titelnummer}}/fetch/{{orderId}}
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

###
