// Ein DAISY Hörbuch direkt abrufen
GET {{host}}/{{api-version}}/hoerbuch/{{titelnummer}}
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

###

// Einen einzelnen Track eines Hörbuchs abrufen
GET {{host}}/{{api-version}}/hoerbuch/{{titelnummer}}/track/{{track}}
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

###
