version: '3.7'

services:
#  cms-backup:
#    image: databack/mysql-backup
#      restart: always
#      volumes:
#        - /local/file/path:/db
#        - /path/to/pre-backup/scripts:/scripts.d/pre-backup
#        - /path/to/post-backup/scripts:/scripts.d/post-backup
#      environment:
#        - TZ=Europe/Berlin
#        - DB_DUMP_TARGET=/db
#        - DB_USER=user123
#        - DB_PASS=pass123
#        - DB_DUMP_FREQ=60
#        - DB_DUMP_BEGIN=2330
#        - DB_SERVER=cms-joomladb
  cms-joomladb:
    image: mysql:5.6
    restart: "no"
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=joomla
      - MYSQL_USER=joomla
      - MYSQL_PASSWORD=joomla
    networks:
      cms-backend:
        ipv4_address: "${CMS_BACKEND_NET}.${JOOMLADB_IP}"
    expose:
      - "${JOOMLADB_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "64m"
        max-file: "7"
  cms-joomla:
    image: joomla:3.9.8-php7.1-fpm-alpine
    depends_on:
      - cms-joomladb
    restart: "no"
    environment:
      - TZ=Europe/Berlin
      - JOOMLA_DB_HOST=joomla-db
      - JOOMLA_DB_USER=joomla
      - JOOMLA_DB_PASSWORD=joomla
    volumes:
      - ./${ENV_NAME}/php.ini:/usr/local/etc/php/php.ini
#      - ./${ENV_NAME}/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - joomla_html:/var/www/html
    networks:
      cms-backend:
        ipv4_address: "${CMS_BACKEND_NET}.${JOOMLA_IP}"
      bookworm-backend:
        ipv4_address: "${HOERBUCHKATALOG_BACKEND_NET}.${JOOMLA_IP}"
      cms-outside:
    expose:
      - "${JOOMLA_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "64m"
        max-file: "7"
  cms-assets:
    build:
      context: ../../
      dockerfile: docker/cms-assets/Dockerfile
    image: wbhonline/cms-assets:${VERSION}
    restart: "no"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - assets_etc_ssh:/etc/ssh:ro
      - joomla_html:/var/www/html:rw
    ports:
      - "${ASSETS_PUBLIC_PORT}:22"
    networks:
      cms-backend:
        ipv4_address: "${CMS_BACKEND_NET}.${ASSETS_IP}"
      cms-public:
    logging:
      driver: "json-file"
      options:
        max-size: "64m"
        max-file: "7"

networks:
  cms-backend:
    name: cms-backend
    driver: bridge
    external: false
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "${CMS_BACKEND_NET}.0/24"
  cms-outside:
    name: cms-outside
    driver: bridge
    external: false
    internal: false
  cms-public:
    name: cms-public
    driver: bridge
    external: false
    internal: false

volumes:
  assets_etc_ssh:
    driver: local
  joomla_html:
    driver: local
