version: '3.7'

services:
  hk-app:
    build:
      context: ../../
      dockerfile: docker/hoerbuchkatalog-app/Dockerfile
    image: wbhonline/hoerbuchkatalog:${VERSION}
    restart: "always"
    environment:
      - HOERBUCHKATALOG_TEMPLATE=/opt/bookworm/var/templates
    volumes:
      - hk_app:/opt/bookworm:ro
      - hk_templates:/opt/bookworm/var/templates:ro
      - hk_wbh:/opt/bookworm/var/wbh:rw
      - hk_blista:/opt/bookworm/var/blista:rw
      - hk_repository:/opt/bookworm/var/repository:rw
    networks:
      bookworm-backend:
        ipv4_address: "${HOERBUCHKATALOG_BACKEND_NET}.${HOERBUCHKATALOG_IP}"
      bookworm-outside:
    expose:
      - ${HOERBUCHKATALOG_PORT}
  hk-datatransfer:
    build:
      context: ../../
      dockerfile: docker/hoerbuchkatalog-datatransfer/Dockerfile
    image: wbhonline/datatransfer:${VERSION}
    restart: "always"
    volumes:
      - hk_datatransfer_etc_ssh:/etc/ssh:ro
      - hk_wbh:/opt/bookworm/var/wbh:rw
    ports:
      - "${DATATRANSFER_PUBLIC_PORT}:22"
    networks:
      - bookworm-public
  hk-admin:
    build:
      context: ../../
      dockerfile: docker/hoerbuchkatalog-admin/Dockerfile
    image: wbhonline/admin:${VERSION}
    restart: "always"
    volumes:
      - hk_admin_etc_ssh:/etc/ssh:ro
      - hk_app:/opt/bookworm:rw
      - hk_templates:/opt/bookworm/var/templates:rw
      - hk_wbh:/opt/bookworm/var/wbh:rw
      - hk_blista:/opt/bookworm/var/blista:rw
      - hk_repository:/opt/bookworm/var/repository:rw
    ports:
      - "${ADMIN_PUBLIC_PORT}:22"
    networks:
      - bookworm-public

volumes:
  hk_admin_etc_ssh:
    driver: local
  hk_datatransfer_etc_ssh:
    driver: local
  hk_app:
    driver: local
  hk_templates:
    driver: local
  hk_repository:
    driver: local
  hk_wbh:
    driver: local
  hk_blista:
    driver: local

networks:
  bookworm-backend:
    name: bookworm-backend
    driver: bridge
    external: false
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "${HOERBUCHKATALOG_BACKEND_NET}.0/24"
  bookworm-outside:
    name: bookworm-outside
    driver: bridge
    external: false
    internal: false
  bookworm-public:
    name: bookworm-public
    driver: bridge
    external: false
    internal: false
