version: '3.7'

services:
  hoerbuchkatalog:
    image: wbh-hbk/hoerbuchkatalog:${hbk.release}
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
      - HOERBUCHKATALOG_TEMPLATE=/var/local/templates
    volumes:
      - hoerbuchkataloglocal:/var/local:rw
    networks:
      - backend
      - frontend
    expose:
      - 8080
  datatransfer-ssh:
    image: wbh-hbk/datatransfer-ssh:${hbk.release}
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
    volumes:
      - hoerbuchkataloglocal:/var/local:rw
    networks:
      - frontend
    expose:
      - 2201
  admin-ssh:
    image: wbh-hbk/admin-ssh:${hbk.release}
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
    volumes:
      - hoerbuchkataloglocal:/var/local:rw
    networks:
      - frontend
    expose:
      - 2202

volumes:
  hoerbuchkataloglocal:
    driver: local

networks:
  backend:
    name: hbk-backend
    driver: bridge
    external: false
    internal: true
  frontend:
    name: hbk-frontend
    driver: bridge
    external: false
    internal: false
