version: '3.7'

services:
  keycloakpostgres:
    image: postgres:${keycloak.postgres.release}
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=Pa55w0rd
    volumes:
      - keycloakpostgresdata:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - ${keycloak.postgres.hostname}
    expose:
      - 5432
  keycloak:
    image: jboss/keycloak:${keycloak.release}
    depends_on:
      - keycloakpostgres
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
      - DB_VENDOR=postgres
      - DB_ADDR=keycloakpostgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - PROXY_ADDRESS_FORWARDING=true
    networks:
      backend:
        aliases:
          - ${keycloak.hostname}
    expose:
      - 8080
  redis:
    image: wbh-hbk/redis:${hbk.release}
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
    volumes:
      - redisdata:/data/redis:rw
    networks:
      - backend
    expose:
      - "6379"
  redisbackup:
    image: wbh-hbk/redisbackup:${hbk.release}
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DIR=/data/redis
      - REDIS_BGSAVE_WAIT=30
      - BACKUP_DIR=/data/backup
    volumes:
      - redisdata:/data/redis:rw
      - redisbackup:/data/backup:rw
    networks:
      - backend
    expose:
      - 6379
  hoerbuchkatalog:
    image: wbh-hbk/hoerbuchkatalog:${hbk.release}
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
      - HOERBUCHKATALOG_TEMPLATE=/var/local/templates
    volumes:
      - hoerbuchkataloglocal:/var/local:rw
    networks:
      - backend
      - frontend
    expose:
      - 1099
      - 5005
      - 8080
  datatransfer-ssh:
    image: wbh-hbk/datatransfer-ssh:${hbk.release}
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
    volumes:
      - datatransfersshconf:/etc/ssh:rw
      - hoerbuchkataloglocal:/var/local/hoerbuchkatalog:rw
    networks:
      - frontend
    expose:
      - 22
  admin-ssh:
    image: wbh-hbk/admin-ssh:${hbk.release}
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
    volumes:
      - adminsshconf:/etc/ssh:rw
      - hoerbuchkataloglocal:/var/local/hoerbuchkatalog:rw
    networks:
      - frontend
    expose:
      - 22

volumes:
  keycloakpostgresdata:
    driver: local
  redisdata:
    driver: local
  redisbackup:
    driver: local
  hoerbuchkataloglocal:
    driver: local
  datatransfersshconf:
    driver: local
  adminsshconf:
    driver: local

networks:
  backend:
    name: hbk-backend
    driver: bridge
    external: false
    internal: true
  frontend:
    name: hbk-frontend
    driver: bridge
    external: false
    internal: false
