version: '3.7'

services:
  datatransfer-ssh:
    ports:
      - "2201:22"
  admin-ssh:
    ports:
      - "2202:22"
  keycloakpostgres:
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=Pa55w0rd
  keycloak:
    environment:
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=Pa55w0rd
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
  hoerbuchkatalog:
    hostname: ${hbk.hostname}
    environment:
      - OAUTH2_BASEURL=https://${keycloak.hostname}/auth
