GET {{host}}/{{context}}/{{api-version}}/hoererarchiv/belastungen
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: 80170

###

GET {{host}}/{{context}}/{{api-version}}/hoererarchiv/bestellkarten
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: 80170

###

GET {{host}}/{{context}}/{{api-version}}/hoererarchiv/erledigteBestellkarten
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: 80170

###
