GET {{host}}/{{context}}/{{api-version}}/katalog/stichwort/Adams
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

###

GET {{host}}/{{context}}/{{api-version}}/katalog/details/21052
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

###
