PUT {{host}}/{{context}}/{{api-version}}/warenkorb
Content-Type: application/json
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

{
    "titelnummer": "21052"
}

###

GET {{host}}/{{context}}/{{api-version}}/warenkorb
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

###

DELETE {{host}}/{{context}}/{{api-version}}/warenkorb
Content-Type: application/json
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

{
    "titelnummer": "21052"
}

###

POST {{host}}/{{context}}/{{api-version}}/warenkorb
Content-Type: application/json
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

{
    "hoerername": "",
    "hoereremail": "ralf@bensmann.com",
    "bemerkung": "",
    "bestellkarteMischen": false,
    "alteBestellkarteLoeschen": false
}
