POST {{host}}/{{context}}/{{api-version}}/warenkorb/21052
Content-Type: application/json
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

###

GET {{host}}/{{context}}/{{api-version}}/warenkorb
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

###

DELETE {{host}}/{{context}}/{{api-version}}/warenkorb/21052
Content-Type: application/json
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

###

POST {{host}}/{{context}}/{{api-version}}/warenkorb/bestellen
Content-Type: application/json
X-Bookworm-Mandant: {{mandant}}
X-Bookworm-Hoerernummer: {{hoerernummer}}

{
    "hoerername": "Herbert Hörer",
    "hoereremail": "herbert@example.com",
    "bemerkung": "",
    "bestellkarteMischen": false,
    "alteBestellkarteLoeschen": false
}
