version: '3.7'

services:
  keycloakpostgres:
    image: postgres:${KEYCLOAK_POSTGRES_RELEASE}
    restart: "no"
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  keycloak:
    image: jboss/keycloak:${KEYCLOAK_RELEASE}
    depends_on:
      - keycloakpostgres
    restart: "no"
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
      - DB_VENDOR=postgres
      - DB_ADDR=keycloakpostgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - KEYCLOAK_STATISTICS=true
    ports:
      - "8081:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
  # hoerbuchdienst
  minio:
    image: minio/minio:latest
    restart: "no"
    command: server /data
    ports:
      - "9000:9000"
  rabbitmq:
    image: rabbitmq:latest
    restart: "no"
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
