version: '3.7'

services:
  # cms
  mysql:
    image: wbh-cms/mysql:${CMS_RELEASE}
    restart: "no"
  joomla:
    image: wbh-cms/joomla:${CMS_RELEASE}
    restart: "no"
  assets-ssh:
    image: wbh-cms/assets-ssh:${CMS_RELEASE}
    restart: "no"
  rproxy:
    image: wbh-cms/rproxy:${CMS_RELEASE}
    restart: "no"
    ports:
      - "8080:80"
      - "8443:443"
  # hoerbuchkatalog
  hoerbuchkatalog:
    image: wbh-hbk/hoerbuchkatalog:${HBK_RELEASE}
    restart: "no"
  datatransfer-ssh:
    image: wbh-hbk/datatransfer-ssh:${HBK_RELEASE}
    restart: "no"
  admin-ssh:
    image: wbh-hbk/admin-ssh:${HBK_RELEASE}
    restart: "no"
  keycloakpostgres:
    image: postgres:${KEYCLOAK_POSTGRES_RELEASE}
    restart: "no"
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"
  keycloak:
    image: jboss/keycloak:${KEYCLOAK_RELEASE}
    depends_on:
      - keycloakpostgres
    restart: "no"
    environment:
      - TZ=Europe/Berlin
      - LANG=en_US.UTF-8
      - DB_VENDOR=postgres
      - DB_ADDR=keycloakpostgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - KEYCLOAK_STATISTICS=true
      #- PROXY_ADDRESS_FORWARDING=true
      #- KEYCLOAK_LOGLEVEL=DEBUG
      #- DEBUG=true
      #- DEBUG_PORT='*:5005'
    #command: -c standalone.xml
    ports:
      - "5005:5005"
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
  # hoerbuchdienst
  vault:
    image: wbh-hbd/vault:${HBD_RELEASE}
    restart: "no"
  kes:
    image: wbh-hbd/kes:${HBD_RELEASE}
    restart: "no"
  minio:
    image: wbh-hbd/minio:${HBD_RELEASE}
    restart: "no"
  mc:
    image: wbh-hbd/mc:${HBD_RELEASE}
    restart: "no"
  rabbitmq:
    image: wbh-hbd/rabbitmq:${HBD_RELEASE}
    restart: "no"
    ports:
      - "5671:5671"
      - "15671:15671"
  #virenscanner:
  #  image: wbh-hbd/virenscanner:${HBD_RELEASE}
  #  restart: "no"
  #  ports:
  #    - "3310:3310"
  hoerbuchdienst:
    image: wbh-hbd/hoerbuchdienst:${HBD_RELEASE}
    restart: "no"
  hbd-rproxy:
    image: wbh-hbd/rproxy:${HBD_RELEASE}
    restart: "no"
    ports:
      - "8081:80"
      - "8444:443"

networks:
  frontend:
    driver: bridge
    external: false
    internal: true
