= WBH Bookworm

== Hörbuchdienst

=== Storage Server provisionieren

netcup Storage Server installieren:
* ArchLinux, minimal * Betriebssystem in kleiner Partition

.shardN: Auf dem Client
Bitte `N` gegen die entsprechende Nummer ersetzen

----
ssh-keygen -R shardN.audiobook.wbh-online.de
ssh-keygen -R <IP Adresse shardN>
ssh-keyscan shardN.audiobook.wbh-online.de 2>/dev/null >>~/.ssh/known_hosts
ssh-keygen -H
ssh-copy-id -i ~/.ssh/id_rsa root@shardN1.audiobook.wbh-online.de <1>
----
<1> Bei Aufforderung das Passwort aus der Konsole des Providers verwenden.

.shardN: SSH Schlüssel generieren
----
ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
cat ~/.ssh/id_rsa.pub
----

und den Public Key auf GitHub und Bitbucket zum Zugriff durch den Server auf den Source Code hinterlegen lassen.

.shardN: WBH Bookworm auschecken
----
ssh-keyscan github.com 2>/dev/null >>~/.ssh/known_hosts
ssh-keyscan bitbucket.org 2>/dev/null >>~/.ssh/known_hosts
git clone git@bitbucket.org:artofcoding/bookworm2 ~/bookworm2
cd ~/bookworm2
git config pull.rebase false
git checkout develop
----

.shardN: Installation Teil 1 -- Die Installation starten:
----
bookworm2 $ bash hoerbuchdienst/bin/setup-storageserver-1.sh
----

und bei Aufforderung Shard Name eingeben (shardN.audiobook.wbh-online.de) und mit der Eingabe 'yes' bestätigen.

Nach erfolgreicher Installation erfolgt automatisch ein Reboot.

.shardN: Installation Teil 2 -- Storage einrichten und Docker installieren:
----
bookworm2 $ bash hoerbuchdienst/bin/setup-storageserver-2.sh
----

=== Applikationen verwalten

==== Installation

Die folgenden Schritte müssen auf einem Shard durchgeführt werden.

.Software für Produktion bauen
----
bookworm2 $ ./build.sh prod
----

Der Release Zeitpunkt kann aus den Logausgaben abgelesen werden.
Alternativ mit `docker image ls` die aktuellsten Images nachschauen.

.Das Deployment durchführen
Dabei den gewünschten Release-Zeitpunkt wählen:

----
bookworm2 $ ./deploy.sh prod hbd 2020-07-16T17-16-39Z
----

.Starten der Applikationen
In das erstellte Release-Verzeichnis wechseln:

----
bookworm2 $ cd ~/releases/prod-hbd-2020-07-16T17-16-39Z/wbh.bookworm.hoerbuchdienst.assembly
releases/prod-hbd-2020-07-16T17-16-39Z/wbh.bookworm.hoerbuchdienst.assembly $ ./lifecycle.sh start
----

==== RabbitMQ

Die Einrichtung von RabbitMQ

.RabbitMQ erstmalig starten
----
docker-compose -p prod-hbd exec rabbitmq rabbitmq-provision.sh
----

.Weitere RabbitMQ Instanzen anbinden
----
docker-compose -p prod-hbd exec rabbitmq rabbitmq-setup-federation.sh \
    "rabbitmq.shard2:user:pwd" \ <1>
    "rabbitmq.shard3:user:pwd"   <2>
----
<1> Ein weiterer, bereits eingerichteter Shard `shard2`
<2> Ein weiterer, bereits eingerichteter Shard `shard3`

Nutzer ist dabei `federator`, das Passwort ist für jeden Shard eigens vergeben.

==== Aktualisierung

tbd

=== Backup

----
/var/lib/docker/volumes/prod-hbd_keslocal/_data/minio.cert
/var/lib/docker/volumes/prod-hbd_keslocal/_data/minio.key
/var/lib/docker/volumes/prod-hbd_keslocal/_data/root.cert
/var/lib/docker/volumes/prod-hbd_keslocal/_data/root.key
/var/lib/docker/volumes/prod-hbd_keslocal/_data/server-config.yml
----

----
echo "MinIO Access Key=$(cat /var/lib/docker/volumes/prod-hbd_miniolocal/_data/access_key)"
echo "MinIO Secret Key=$(cat /var/lib/docker/volumes/prod-hbd_miniolocal/_data/secret_key)"
echo "MinIO Admin Access Key=$(head -1 /var/lib/docker/volumes/prod-hbd_mclocal/_data/user_admin)"
echo "MinIO Admin Secret Key=$(tail -1 /var/lib/docker/volumes/prod-hbd_mclocal/_data/user_admin)"
echo "MinIO WBH Access Key=$(head -1 /var/lib/docker/volumes/prod-hbd_mclocal/_data/user_wbh)"
echo "MinIO WBH Secret Key=$(tail -1 /var/lib/docker/volumes/prod-hbd_mclocal/_data/user_wbh)"
----

----
cat /var/lib/docker/volumes/prod-hbd_vaultconfig/_data/vault-operator-init.txt
cat /var/lib/docker/volumes/prod-hbd_vaultconfig/_data/kes-role-id.json
cat /var/lib/docker/volumes/prod-hbd_vaultconfig/_data/kes-secret-id.json
----
