version: '3.7'

services:
  mysql:
    image: wbh-cms/mysql:${cms.release}
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=joomla
      - MYSQL_USER=joomla
      - MYSQL_PASSWORD=joomla
    volumes:
      - mysqldata:/var/lib/mysql:rw
    networks:
      - backend
    expose:
      - 3306
  joomla:
    image: wbh-cms/joomla:${cms.release}
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - TZ=Europe/Berlin
      - JOOMLA_DB_HOST=mysql
      - JOOMLA_DB_USER=joomla
      - JOOMLA_DB_PASSWORD=joomla
    volumes:
      - joomladata:/var/www/html:rw
    networks:
      - backend
      - frontend
    expose:
      - 9000
  assets-ssh:
    image: wbh-cms/assets-ssh:${cms.release}
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - joomladata:/var/www/html:rw
    networks:
      - backend
    ports:
      - "2203:22"
  cms-rproxy:
    image: wbh-cms/rproxy:${cms.release}
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - rproxycerts:/etc/letsencrypt:rw
      - joomladata:/var/www/html:ro
    networks:
      #- proxy-hbk-backend
      - hbk-backend
      - backend
      - frontend
  #rproxy-certbot:
  #  image: wbh-cms/rproxy-certbot:${cms.release}
  #  restart: unless-stopped
  #  depends_on:
  #    - cms-rproxy
  #  environment:
  #    - TZ=Europe/Berlin
  #  volumes:
  #    - rproxyconf:/etc/nginx:rw
  #    - rproxycerts:/etc/letsencrypt:rw
  #  networks:
  #    - hbk-backend

networks:
  #proxy-hbk-backend:
  #  external:
  #    name: hbk-backend
  hbk-backend:
    name: hbk-backend
    driver: bridge
    external: false
    internal: true
  backend:
    name: cms-backend
    driver: bridge
    external: false
    internal: true
  frontend:
    name: cms-frontend
    driver: bridge
    external: false
    internal: false

volumes:
  mysqldata:
    driver: local
  joomladata:
    driver: local
  rproxycerts:
    driver: local
