version: '3.7'
services:
  hoerbuchkatalog:
    image: wbh/hoerbuchkatalog:latest
    ports:
      - 80:9080
    environment:
      - HOERBUCHKATALOG_TEMPLATE=./template
    volumes:
      - var_hoerbuchkatalog:/var/hoerbuchkatalog
      - var_nutzerbereich:/var/nutzerbereich
  nginx:
    image: nginx/stable-alpine:latest
    ports:
      - 443:443
networks:
  frontend:
    name: frontend
    driver: bridge
    external: true
  private:
    name: private
    driver: bridge
    external: false
volumes:
  hoerbuchkatalog_data:
    driver: local
  nutzerbereich_data:
    driver: local
