FROM openjdk:11.0.1-jdk-slim-stretch
MAINTAINER Ralf Bensmann <ralf@art-of-coding.eu>
LABEL vendor="Art of Coding UG"

ENV buildNumber=LocalBuild
RUN echo Build number is $buildNumber

WORKDIR /opt/hoerbuchkatalog
COPY assembly/target/wbh.bookworm.hoerbuchkatalog.assembly.jar .
COPY assembly/src/main/resources/conf conf
COPY assembly/src/main/resources/application*.yml ./
VOLUME ["/var/templates", "/var/wbh"]
COPY assembly/var/hoerbuchkatalog/Gesamt*.dat ./var/wbh/hoerbuchkatalog/
COPY assembly/var/nutzerdaten/*.csv ./var/wbh/nutzerdaten/
COPY ui/src/main/resources/templates /var/templates
ENV HOERBUCHKATALOG_TEMPLATE /var/templates

HEALTHCHECK NONE

EXPOSE 9080/tcp

RUN ls -lR

CMD ["java", \
    "-Xms2G", "-Xmx2G", \
    "-jar", "wbh.bookworm.hoerbuchkatalog.assembly.jar", \
    "--spring.profiles.active=development", \
    "--spring.config.additional-location=conf/" \
]
