version: '3.7'
services:
  datatransfer:
    image: wbh/datatransfer:latest
    ports:
      - 2201:22
    networks:
      - public
  hoerbuchkatalog-app:
    image: wbh/hoerbuchkatalog:latest
    ports:
      - 9080:9080
    environment:
      - HOERBUCHKATALOG_TEMPLATE=./template
    volumes:
      - var_hoerbuchkatalog:/var/hoerbuchkatalog
      - var_nutzerbereich:/var/nutzerbereich
    networks:
      - private
  hoerbuchkatalog-web:
    image: wbh/reverse-proxy:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - public
      - private
networks:
  frontend:
    name: frontend
    driver: bridge
    external: true
  private:
    name: private
    driver: bridge
    external: false
volumes:
  datatransfer_etc_ssh:
    driver: local
  var_hoerbuchkatalog:
    driver: local
  var_nutzerbereich:
    driver: local
