FROM alpine:3.9
MAINTAINER Ralf Bensmann <ralf@art-of-coding.eu>
LABEL vendor="Art of Coding UG"

#RUN echo "root:root" | chpasswd

# https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management
# https://www.cyberciti.biz/faq/10-alpine-linux-apk-command-examples/
RUN apk update \
    && apk add openssh \
    && rm -rf /var/cache/apk/* \
    && sed -i'' -E \
        -e 's/^#(PermitRootLogin|HostKey)/\1/' \
        -e 's/^#(ListenAddress 0|ListenAddress ::|Port)/\1/' \
        /etc/ssh/sshd_config \
    && sed -i'' -E \
        -e 's#^\(PermitRootLogin \).*#\1 without-password#' \
        -e 's#\(ListenAddress \).*#\1 0.0.0.0#' \
        -e 's#\(Port \).*#\1 22#' \
        /etc/ssh/sshd_config \
    && ssh-keygen -A \
    && ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_key

VOLUME ["/etc/ssh"]

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
