shard:
  name: shard0
  domain: local

micronaut:
  server:
    max-request-size: 3072mb
    multipart:
      max-file-size: 3072mb
  http:
    client:
      read-timeout: 300

hoerbuchdienst:
  objectstorage:
    path: /Users

rabbitmq:
  servers:
    default:
      uri: amqp://bugs:bunny@localhost/hoerbuchdienst
      #uri: amqps://nnn:nnn@rabbitmq.${shard.name}.${shard.domain}/hoerbuchdienst
      #uri: amqps://nnn:nnn@rabbitmq.shard2.audiobook.wbh-online.de/hoerbuchdienst

objectstorage:
  minio:
    url: http://minio.shard0.local:9000
    access_key: AKIAIOSFODNN7EXAMPLE
    secure_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
