micronaut:
  application:
    name: hoerbuchdienst
  server:
    host: localhost
    port: 8080
    context-path: /
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"
  views:
    csp:
      enabled: true
  caches:
    audiobookRepository:
      maximumSize: 2
  jcache:
    enabled: true

hoerbuchdienst:
  repository:
    type: objectstorage
    localdisk:
      uri: ../../../Buecher-WBH
    objectstorage:
      name: minio
  temporary:
    path: /tmp/hoerbuchdienst

objectstorage:
  minio:
    url: https://minio.${shard.name}.local
    accessKey: AKIAIOSFODNN7EXAMPLE
    secureKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    bucketName: hoerbuchdienst
    serversideencryption: atRest

rabbitmq:
  servers:
    default:
      uri: amqps://${rabbitmq.username:bugs}:${rabbitmq.password:bunny}@rabbitmq.${shard.name}.local/hoerbuchdienst
      automatic-recovery-enabled: true

elasticsearch:
  httpHosts: "http://elasticsearch:9200"
