micronaut:
  application:
    name: hoerbuchdienst
  server:
    host: localhost
    port: 8080
    context-path: /
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"
  views:
    csp:
      enabled: true
  caches:
    audiobookRepository:
      maximumSize: 20
  jcache:
    enabled: true

hoerbuchdienst:
  repository:
    type: objectstorage
    localdisk:
      uri: ../../../Buecher-WBH
    objectstorage:
      name: minio
  temporary:
    path: /tmp/hoerbuchdienst

objectstorage:
  minio:
    url: https://s3.medienhof9.rootaid.de
    accessKey: Nae3bahcexie9eifaihe
    secureKey: eenieth9hoquohcooyeiRukoxopooPheew3caip7
    bucketName: hoerbuchdienst
    serversideencryption: atRest

elasticsearch:
  httpHosts: "http://localhost:9200,http://127.0.0.1:9200"
