micronaut:
  server:
    host: localhost
    port: 8090

hoerbuchdienst:
  repository:
    localdisk:
      uri: /tmp/Buecher-WBH

hoerbuchkatalog:
  url: http://localhost:8080

elasticsearch:
  httpHosts: "http://localhost:9200"

logger:
  levels:
    root: INFO
    wbh.bookworm.hoerbuchdienst.adapter.provided.api: DEBUG
    wbh.bookworm.hoerbuchdienst.adapter.provided.katalog: DEBUG
    wbh.bookworm.hoerbuchdienst.adapter.provided.sharding: DEBUG
    wbh.bookworm.hoerbuchdienst.adapter.provided.stream: DEBUG
    wbh.bookworm.hoerbuchdienst.adapter.required.daisy: DEBUG
    wbh.bookworm.hoerbuchdienst.adapter.required.watermark: DEBUG
    wbh.bookworm.hoerbuchdienst.adapter.required.hoerbuchkatalog: DEBUG
    wbh.bookworm.hoerbuchdienst.application: DEBUG
    wbh.bookworm.hoerbuchdienst: DEBUG
    io.micronaut.web.router: ERROR
    io.micronaut.web: ERROR
    io.micronaut.http.server: ERROR
    io.micronaut.http: ERROR
    io.micronaut.scheduling: ERROR
    io.micronaut.rabbitmq: ERROR
    io.micronaut.context.condition: ERROR
    io.micronaut.context.env: ERROR
    io.micronaut.context: ERROR
    io.micronaut.core.reflect: ERROR
    io.micronaut.core: ERROR
    io.micronaut: ERROR
    io.netty: ERROR
