micronaut:
  application:
    name: hoerbuchdienst
  server:
    port: 8080
    context-path: /
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"
  views:
    csp:
      enabled: true
  caches:
    audiobookRepository:
      maximumSize: 20
  jcache:
    enabled: true

hoerbuchdienst:
  repository:
    type: objectstorage
    localdisk:
      uri: /path/to/Buecher-WBH
    objectstorage:
      name: minio
  temporary:
    path: ${java.io.tmpdir}/hoerbuchdienst
  piracy:
    inquiry:
      urlprefix: https://wbh-online.de/ausleihe-anfragen

objectstorage:
  minio:
    bucketName: hoerbuchdienst
    serversideencryption: atRest

rabbitmq:
  servers:
    default:
      automatic-recovery-enabled: true
