shard:
  name: shard0
  domain: local

hoerbuchdienst:
  repository:
    type: objectstorage
    localdisk:
      uri: /path/to/Buecher-WBH
    objectstorage:
      name: minio
  objectstorage:
    path: /Users
  temporary:
    path: ${java.io.tmpdir}/hoerbuchdienst
  piracy:
    inquiry:
      urlprefix: https://wbh-online.de/q-ausleihe

objectstorage:
  minio:
    url: http://localhost:9000
    access_key: minioadmin
    secure_key: minioadmin
    bucketName: hoerbuchdienst
    serversideencryption: atRest

rabbitmq:
  servers:
    default:
      automatic-recovery-enabled: true
      uri: amqp://guest:guest@localhost
      #uri: amqps://nnn:nnn@rabbitmq.${shard.name}.${shard.domain}/hoerbuchdienst
      #uri: amqps://nnn:nnn@rabbitmq.shard2.wbh-online.de/hoerbuchdienst

micronaut:
  application:
    name: hoerbuchdienst
  server:
    context-path: /
    max-request-size: 1mb
    multipart:
      max-file-size: 1mb
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      #swagger-ui:
      #  paths: classpath:META-INF/swagger/views/swagger-ui
      #  mapping: /swagger-ui/**
  views:
    csp:
      enabled: true
  caches:
    audiobookRepository:
      maximumSize: 10
  jcache:
    enabled: true
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      oauth:
        enabled: false
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
      - pattern: /rapidoc/**
        access:
          - isAnonymous()
      - pattern: /redoc/**
        access:
          - isAnonymous()
