shard:
  name: shard0
  domain: local

rabbitmq:
  servers:
    default:
      uri: amqp://guest:guest@localhost
      #uri: amqps://nnn:nnn@rabbitmq.${shard.name}.${shard.domain}/hoerbuchdienst
      #uri: amqps://nnn:nnn@rabbitmq.shard2.wbh-online.de/hoerbuchdienst

objectstorage:
  minio:
    url: http://localhost:9000
    access_key: minioadmin
    secure_key: minioadmin
