micronaut:
  server:
    host: 0.0.0.0
  http:
    client:
      read-timeout: 300

hoerbuchdienst:
  repository:
    localdisk:
      uri: /var/local/Buecher-WBH

elasticsearch:
  httpHosts: "http://elasticsearch:9200"
