version: '3.7'

services:
  rproxy:
    build:
      context: ../../
      dockerfile: docker/rproxy/Dockerfile
    image: wbhonline/rproxy:${VERSION}
    restart: "always"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - rproxy_etc_nginx:/etc/nginx:rw
      - rproxy_etc_letsencrypt:/etc/letsencrypt:ro
      - joomla_html:/var/www/html:ro
    networks:
      cms-backend:
        ipv4_address: "${CMS_BACKEND_NET}.${RPROXY_IP}"
      bookworm-backend:
        ipv4_address: "${HOERBUCHKATALOG_BACKEND_NET}.${RPROXY_IP}"
#      bookworm-secure:
#        ipv4_address: "${HOERBUCHKATALOG_SECURE_NET}.${RPROXY_IP}"
      bookworm-public:
    ports:
      - "${RPROXY_PUBLIC_HTTP_PORT}:80"
      - "${RPROXY_PUBLIC_HTTPS_PORT}:443"
  rproxy-certbot:
    build:
      context: ../../
      dockerfile: docker/rproxy-certbot/Dockerfile
    image: wbhonline/rproxy-certbot:${VERSION}
    restart: "always"
    depends_on:
      - rproxy
    environment:
      - TZ=Europe/Berlin
    volumes:
      - rproxy_etc_nginx:/etc/nginx:rw
      - rproxy_etc_letsencrypt:/etc/letsencrypt:rw

volumes:
  rproxy_etc_nginx:
    driver: local
  rproxy_etc_letsencrypt:
    driver: local

networks:
  bookworm-public:
    name: bookworm-public
    driver: bridge
    external: false
    internal: false
