version: '3.7'

services:
  rproxy:
    build:
      context: ""
      dockerfile: Dockerfile
    image: wbhonline/rproxy:${VERSION}
    restart: "no"
    volumes:
      - rproxy_etc_nginx:/etc/nginx:rw
      - rproxy_certs:/etc/letsencrypt:rw
      - joomla_html:/var/www/html:ro
    networks:
      cms-backend:
        ipv4_address: "172.16.47.2"
      bookworm-backend:
        ipv4_address: "172.16.48.2"
      bookworm-secure:
        ipv4_address: "172.16.1.2"
      bookworm-public:
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5m0s
      timeout: 1s
      retries: 3
      start_period: 60s

networks:
  bookworm-public:
    name: bookworm-public
    driver: bridge
    external: false
    internal: false

volumes:
  rproxy_etc_nginx:
    driver: local
  rproxy_certs:
    driver: local
