version: '3.7'

services:
  vault:
    build:
      context: ../bookworm-vault
      dockerfile: Dockerfile
    image: bookworm/vault:LocalBuild
    networks:
      bookworm-backend:
        ipv4_address: "192.168.48.3"
    ports:
      - "8200:8200"
    volumes:
      - vault:/opt/vault
#    environment:
#      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/opt/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
  hoerbuchkatalog:
    build:
      context: ../../
      dockerfile: docker/bookworm-hoerbuchkatalog/Dockerfile
    image: bookworm/hoerbuchkatalog:LocalBuild
    restart: "no"
    depends_on:
      - vault
    environment:
      - HOERBUCHKATALOG_TEMPLATE=/opt/bookworm/var/templates
    volumes:
      - app:/opt/bookworm
      - templates:/opt/bookworm/var/templates
      - wbh:/opt/bookworm/var/wbh
      - blista:/opt/bookworm/var/blista
      - repository:/opt/bookworm/var/repository
    networks:
      bookworm-outside:
      bookworm-backend:
        ipv4_address: "192.168.48.4"
    expose:
      - 9080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5m0s
      timeout: 1s
      retries: 3
      start_period: 60s
  admin:
    build:
      context: ../../
      dockerfile: docker/bookworm-admin/Dockerfile
    image: bookworm/admin:LocalBuild
    depends_on:
      - hoerbuchkatalog
    restart: "no"
    ports:
      - "2202:22"
    volumes:
      - admin_etc_ssh:/etc/ssh
      - app:/opt/bookworm
      - templates:/opt/bookworm/var/templates
      - wbh:/opt/bookworm/var/wbh
      - blista:/opt/bookworm/var/blista
      - repository:/opt/bookworm/var/repository
    networks:
      - bookworm-public
  datatransfer:
    build:
      context: ../../
      dockerfile: docker/bookworm-datatransfer/Dockerfile
    image: bookworm/datatransfer:LocalBuild
    depends_on:
      - hoerbuchkatalog
    restart: "no"
    ports:
      - "2201:22"
    volumes:
      - datatransfer_etc_ssh:/etc/ssh
      - wbh:/opt/bookworm/var/wbh
    networks:
      - bookworm-public
  rproxy:
    build:
      context: ../../
      dockerfile: docker/bookworm-rproxy/Dockerfile
    image: bookworm/rproxy:LocalBuild
    depends_on:
      - hoerbuchkatalog
    restart: "no"
    volumes:
      - rproxy_etc_nginx:/etc/nginx
    networks:
      bookworm-backend:
        ipv4_address: "192.168.48.2"
      bookworm-public:
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5m0s
      timeout: 1s
      retries: 3
      start_period: 60s

networks:
  bookworm-backend:
    name: bookworm-backend
    driver: bridge
    external: false
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "192.168.48.0/24"
  bookworm-outside:
    name: bookworm-outside
    driver: bridge
    external: false
    internal: false
  bookworm-public:
    name: bookworm-public
    driver: bridge
    external: false
    internal: false

volumes:
  admin_etc_ssh:
    driver: local
  datatransfer_etc_ssh:
    driver: local
  vault:
    driver: local
  app:
    driver: local
  templates:
    driver: local
  wbh:
    driver: local
  blista:
    driver: local
  repository:
    driver: local
  rproxy_etc_nginx:
    driver: local
