version: '3.7'

services:
  wbh-online-cms:
    image: joomla:3.9.3-fpm-alpine
    depends_on:
      - wbh-online-db
    restart: "no"
    environment:
      JOOMLA_DB_HOST: wbh-online-db
      JOOMLA_DB_PASSWORD: example
    networks:
      - cms-backend
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5m0s
      timeout: 1s
      retries: 3
      start_period: 60s
  wbh-online-db:
    image: mysql:5.6
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - cms-backend
    expose:
      - "3306"
  vault:
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
  bookworm-hoerbuchkatalog:
    build:
      context: ../../
      dockerfile: docker/bookworm-hoerbuchkatalog/Dockerfile
    image: bookworm/hoerbuchkatalog:LocalBuild
    restart: "no"
    environment:
      - HOERBUCHKATALOG_TEMPLATE=/opt/bookworm/var/templates
    volumes:
      - bookworm_app:/opt/bookworm/app
      - bookworm_templates:/opt/bookworm/var/templates
      - bookworm_wbh:/opt/bookworm/var/wbh
      - bookworm_blista:/opt/bookworm/var/blista
      - bookworm_repository:/opt/bookworm/var/repository
    networks:
      bookworm-backend:
        ipv4_address: "192.168.48.3"
    expose:
      - "9080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.48.3:80"]
      interval: 5m0s
      timeout: 1s
      retries: 3
      start_period: 60s
  bookworm-datatransfer:
    build:
      context: ../../
      dockerfile: docker/bookworm-datatransfer/Dockerfile
    image: bookworm/datatransfer:LocalBuild
    depends_on:
      - bookworm-hoerbuchkatalog
    restart: "no"
    ports:
      - "2201:22"
    volumes:
      - bookworm_templates:/opt/bookworm/var/templates
      - bookworm_wbh:/opt/bookworm/var/wbh
    networks:
      - bookworm-public
  bookworm-admin:
    build:
      context: ../../
      dockerfile: docker/bookworm-admin/Dockerfile
    image: bookworm/admin:LocalBuild
    depends_on:
      - bookworm-hoerbuchkatalog
    restart: "no"
    ports:
      - "2202:22"
    volumes:
      - bookworm_app:/opt/bookworm/app
      - bookworm_templates:/opt/bookworm/var/templates
      - bookworm_wbh:/opt/bookworm/var/wbh
      - bookworm_blista:/opt/bookworm/var/blista
      - bookworm_repository:/opt/bookworm/var/repository
    networks:
      - bookworm-public
  bookworm-rproxy:
    build:
      context: ../../
      dockerfile: docker/bookworm-rproxy/Dockerfile
    image: bookworm/rproxy:LocalBuild
    depends_on:
      - bookworm-hoerbuchkatalog
    restart: "no"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - rproxy_etc_nginx:/etc/nginx
    networks:
      cms-backend:
      bookworm-backend:
        ipv4_address: "192.168.48.2"
      bookworm-public:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.48.2:80"]
      interval: 5m0s
      timeout: 1s
      retries: 3
      start_period: 60s

networks:
  cms-backend:
    name: cms-backend
    driver: bridge
    external: false
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "192.168.47.0/24"
  bookworm-backend:
    name: bookworm-backend
    driver: bridge
    external: false
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "192.168.48.0/24"
  bookworm-public:
    name: bookworm-public
    driver: bridge
    external: false
    internal: false

volumes:
  admin_etc_ssh:
    driver: local
  datatransfer_etc_ssh:
    driver: local
  bookworm_app:
    driver: local
  bookworm_templates:
    driver: local
  bookworm_wbh:
    driver: local
  bookworm_blista:
    driver: local
  bookworm_repository:
    driver: local
  rproxy_etc_nginx:
    driver: local
