shard:
  name: shardN

rabbitmq:
  servers:
    default:
      uri: amqps://username:password@rabbitmq.${shard.name}.audiobook.wbh-online.de/hoerbuchdienst

objectstorage:
  minio:
    url: http://minio:9000
    access_key:
    secure_key:
