shard:
  name: shardN
  domain: wbh-online.de

rabbitmq:
  servers:
    default:
      uri: amqps://username:password@rabbitmq-${shard.name}.${shard.domain}/hoerbuchdienst

objectstorage:
  minio:
    url: http://minio:9000
    access_key:
    secure_key:
