version: '3.7'

services:
  mysql:
    image: mysql:5.6
    restart: "no"
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=joomla
      - MYSQL_USER=joomla
      - MYSQL_PASSWORD=joomla
    volumes:
      - ./tmp/mysqldata:/var/lib/mysql:rw
    expose:
      - 3306
  joomla:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    depends_on:
      - mysql
    environment:
      - TZ=Europe/Berlin
      - JOOMLA_DB_HOST=mysql
      - JOOMLA_DB_USER=joomla
      - JOOMLA_DB_PASSWORD=joomla
    volumes:
      - ./tmp/joomla3.9.22:/var/www/html:rw
    expose:
      - 9000
