FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.7
#FROM docker.elastic.co/elasticsearch/elasticsearch:7.6.1

ENV discovery.type=single-node
ENV cluster.name=elasticsearch-docker
ENV node.name=es01

EXPOSE 9200 9300
