version: '3.7'

services:
  datatransfer:
    image: wbh/datatransfer:latest
    ports:
      - 2201:22
    volumes:
      - var_wbh:/var/wbh
    networks:
      public
  hoerbuchkatalog-app:
    image: wbh/hoerbuchkatalog:latest
    ports:
      - 9080:9080
    environment:
      - HOERBUCHKATALOG_TEMPLATE=/var/template
    volumes:
      - var_template:/var/template
      - var_wbh:/var/wbh
    networks:
      - private
  hoerbuchkatalog-rproxy:
    image: wbh/rproxy:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - public
      - private

networks:
  public:
    name: public
    driver: bridge
    internal: false
    driver_opts:
      com.docker.network.enable_ipv6: true
  private:
    name: private
    driver: bridge
    internal: true

volumes:
  datatransfer_etc_ssh:
    driver: local
  var_templates:
    driver: local
  var_wbh:
    driver: local
  rproxy_etc_nginx:
    driver: local
