OAUTH2_BASEURL:
OAUTH2_REALM: Bookworm
OAUTH2_CLIENT_ID: wbh-admin
OAUTH2_CLIENT_SECRET: b1e2b616-192d-4383-96e4-e4c9f6b63ace

hoerbuchkatalog:
  directory: /var/local/wbh/hoerbuchkatalog
  cron:
    expression: 0 15 5 * * MON-FRI
  suchergebnisse:
    anzahl: 1000
  wbh:
    gesamtdat:
      filename: Gesamt.dat
      charset: ISO-8859-15

hoererdaten:
  directory: /var/local/wbh/nutzerdaten

cdlieferung:
  directory: /var/local/wbh/nutzerdaten

repository:
  path: /var/local

lucene:
  index:
    directory: ${hoerbuchkatalog.directory}/lucene

spring:
  redis:
    host: redis
  mail:
    host:
    port:
    username:
    password:

server:
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never

logging:
  level:
    root: ERROR
    wbh.bookworm.hoerbuchkatalog.assembly: INFO
    wbh.bookworm.hoerbuchkatalog.webservice: INFO
    wbh.bookworm.hoerbuchkatalog.app: INFO
    wbh.bookworm.hoerbuchkatalog.repository: INFO
    wbh.bookworm.hoerbuchkatalog.domain: INFO
    wbh.bookworm.hoerbuchkatalog: INFO
    aoc.mikrokosmos.io.dataformat.CsvFormat: INFO
    aoc.mikrokosmos.io.dataformat.LineFileParser: INFO
    aoc.mikrokosmos.io: INFO
    aoc.mikrokosmos.fs: INFO
    aoc.mikrokosmos.ddd.event: INFO
    aoc.mikrokosmos.ddd.repository: INFO
    aoc.mikrokosmos.ddd.search: INFO
    aoc.mikrokosmos: INFO
    eu.artofcoding: INFO
    org.keycloak: ERROR
    org.eclipse.jetty: ERROR
    org.springframework.boot.web.embedded.jetty: ERROR
    org.springframework.boot.actuator: ERROR
    org.springframework.web.servlet.handler: ERROR
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: INFO
    org.springframework.web.servlet.mvc.method: INFO
    org.springframework.web: INFO
    org.springframework.security.web.access.expression.ExpressionBasedFilterInvocationSecurityMetadataSource: INFO
    org.springframework.security: INFO
    org.springframework.scheduling: ERROR
    org.springframework.beans.factory.support: ERROR
    org.springframework.beans: ERROR
    org.springframework: ERROR
    org.reflections: ERROR
