hoerbuchkatalog:
  directory: ./var/wbh/hoerbuchkatalog
  cron:
    expression: 0 15 5 * * MON-FRI
  suchergebnisse:
    anzahl: 1000
  wbh:
    gesamtdat:
      filename: Gesamt.dat
      charset: ISO-8859-15

hoererdaten:
  directory: ./var/wbh/nutzerdaten

cdlieferung:
  directory: ./var/wbh/nutzerdaten

repository:
  path: ./var

lucene:
  index:
    directory: ${hoerbuchkatalog.directory}/lucene

spring:
  redis:
    host:
    port: 6379
  mail:
    default-encoding: UTF-8
    host:
    protocol: smtp
    test-connection: true
    properties:
      mail:
        debug: false
        smtp:
          debug: false
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  compression:
    enabled: false
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
  servlet:
    context-path: /hoerbuchkatalog
  http2:
    enabled: true

logging:
  level:
    root: ERROR
    wbh.bookworm.hoerbuchkatalog.assembly: ERROR
    wbh.bookworm.hoerbuchkatalog.rest: ERROR
    wbh.bookworm.hoerbuchkatalog.app: ERROR
    wbh.bookworm.hoerbuchkatalog.repository: ERROR
    wbh.bookworm.hoerbuchkatalog.domain: ERROR
    aoc.mikrokosmos: ERROR
    aoc.mikrokosmos.fs: ERROR
    aoc.mikrokosmos.ddd.event: ERROR
    aoc.mikrokosmos.ddd.repository: ERROR
    aoc.mikrokosmos.ddd.search: ERROR
    eu.artofcoding: ERROR
    org.eclipse.jetty: ERROR
    org.springframework.web.servlet.handler: ERROR
    org.springframework.web: ERROR
    org.springframework.scheduling: ERROR
    org.springframework.beans.factory.support: ERROR
    org.springframework: ERROR
    org.reflections: ERROR
