version: '3.7'
services:
  docker-registry:
    image: registry:latest
    ports:
      - 5000:5000
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5001
    volumes:
      - docker_registry_data:/registry
  postgresql:
    image: bitnami/postgresql:10
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/bitnami
  sonarqube:
    image: bitnami/sonarqube:latest
    ports:
      - 9000:9000
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1234
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bitnami1234
    volumes:
      - sonarqube_data:/bitnami
networks:
  frontend:
    name: frontend
    driver: bridge
    external: true
  private:
    name: private
    driver: bridge
    external: false
volumes:
  docker_registry_data:
    driver: local
  postgresql_data:
    driver: local
  sonarqube_data:
    driver: local
