version: '3.7'

services:
  vault:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - bookworm_vault:/vault
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
