version: '3.7'

services:
  portainer:
  vault:
  kes:
  minio:
  mc:
  rabbitmq:
    ports:
      - "5671:5671"
      - "15671:15671"
  #virenscanner:
  #keycloakpostgres:
  #keycloak:
  hoerbuchdienst:
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 1073741824 # 1 GB
  hbd-rproxy:
    ports:
      - "80:80"
      - "443:443"
