version: '3.8'

services:
  vault:
    build:
      context: vault
  kes:
    build:
      context: kes
  minio:
    build:
      context: minio
  mc:
    build:
      context: mc
  rabbitmq:
    build:
      context: rabbitmq
  virenscanner:
    build:
      context: virenscanner
  hoerbuchdienst:
  hbd-rproxy:
    build:
      context: rproxy
