version: '3.8'

services:
  portainer:
    ports:
      - "9090:9000"
  vault:
    ports:
      - "8200:8200"
  kes:
  minio:
    ports:
      - "9000:9000"
  mc:
  rabbitmq:
    ports:
      - "5671:5671"
      - "15671:15671"
  #virenscanner:
  #  ports:
  #    - "3310:3310"
  #keycloakpostgres:
  #keycloak:
  hoerbuchdienst:
    #volumes:
    #  - type: tmpfs
    #    target: /tmp
    #    tmpfs:
    #      size: 104857600 # 100 MB
    ports:
      - "8080:8080"
  hbd-rproxy:
    ports:
      - "80:80"
      - "443:443"
