address: 0.0.0.0:7373
root: ROOT_IDENTITY

tls:
  key: ${tls.path}/${kes.hostname}/privkey.pem
  cert: ${tls.path}/${kes.hostname}/cert.pem

policy:
  minio:
    paths:
      - /v1/key/create/minio-*
      - /v1/key/generate/minio-*
      - /v1/key/decrypt/minio-*
    identities:
      - APP_IDENTITY

cache:
  expiry:
    any: 5m0s
    unused: 20s

keys:
  vault:
    endpoint: https://${vault.hostname}:8200
    prefix: minio
    approle:
      id: APPROLE_ID
      secret: APPROLE_SECRET_ID
      retry: 15s
    status:
      ping: 10s
    tls:
      ca: ${tls.path}/${vault.hostname}/cert.pem

log:
  error: on
  audit: off
