version: '3.8'

services:
  maven:
    build:
      context: openjdk11-maven-docker
    image: wbh-bookworm/builder:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - m2cache:/var/local/.m2

volumes:
  m2cache:
    driver: local
