POST /resharding/zip/{titelnummer}/{hash}
Content-Type: application/json

{
}

###

POST /info/audiobook
Content-Type: application/json

{
}

###

POST /info/playlist
Content-Type: application/json

{
}

###

POST /info/track
Content-Type: application/json

{
}

###

HEAD http://localhost:8080/stream/location/32905

###

#HEAD https://hoerbuchdienst.shard1.audiobook.wbh-online.de/stream/location/00001
HEAD http://localhost:8080/stream/location/00001

###

#POST https://hoerbuchdienst.shard1.audiobook.wbh-online.de/stream/zip
POST http://localhost:8080/stream/zip
Content-Type: application/json

{
    "mandant": "WBH",
    "hoerernummer": "80170",
    "aghNummer": "",
    "titelnummer": "32909"
}

###

#POST https://hoerbuchdienst.shard1.audiobook.wbh-online.de/stream/zip/order
POST http://localhost:8080/stream/zip/order
Content-Type: application/json

{
    "mandant": "WBH",
    "hoerernummer": "80170",
    "aghNummer": "",
    "titelnummer": "32909"
}

###

GET http://localhost:8080/stream/zip/status

###

GET http://localhost:8080/stream/zip/fetch/

###

#POST https://hoerbuchdienst.shard1.audiobook.wbh-online.de/stream/track
POST http://localhost:8080/stream/track
Content-Type: application/json

{
    "mandant": "WBH",
    "hoerernummer": "00001",
    "titelnummer": "32909",
    "ident": "01_Halt_die_Wolken_fest.mp3"
}

###
