// Ein Hörbuch mit Wasserzeichen bestellen
POST {{host}}/bestellung/zip
Content-Type: application/json

{
    "mandant": "{{mandant}}",
    "hoerernummer": "{{hoerernummer}}",
    "aghNummer": "",
    "titelnummer": "{{titelnummer}}"
}

> {% client.global.set("orderId", response.body.json); %}

###

//  Den Status einer Bestellung eines Hörbuchs mit Wasserzeichen abfragen
GET {{host}}/bestellung/zip/{{titelnummer}}/status/{{orderId}}

###

//  Eine zuvor bestelltes Hörbuch mit Wasserzeichen abrufen
GET {{host}}/bestellung/zip/{{titelnummer}}/fetch/{{orderId}}

###
