// Den Shard für ein Hörbuch erfragen
GET {{host}}/{{api-version}}/shard/location/{{titelnummer}}

###

// Ein Hörbuch aufgrund von Resharding zum Shard senden
POST {{host}}/{{api-version}}/shard/redistribute/zip/{{titelnummer}}/{hash}
Content-Type: application/octet-stream

binaryData...

###
