@startuml

!include plantuml/Skinparams.iuml

component "Client mit\nClient Credentials Flow" as IDP_ClientCredentials <<ID Provider>> {
}
component "Client mit\nAuthorization Code Flow" as IDP_AuthorizationCode <<ID Provider>> {
}

component "Hoerbuchkatalog" as HBK {
    component webservice <<Adapter>> {
    }
    webservice -l- IDP_ClientCredentials
    component adminui <<Adapter>> {
    }
    adminui -r- IDP_AuthorizationCode
    rectangle Domain {
        component app <<module>> {
        }
        component domain <<module>> {
        }
        component repository <<module>> {
        }
        database Katalog
        repository -r- Katalog
        database Hoererdaten
        repository -l- Hoererdaten
        database Downloads
        repository -d- Downloads
        adminui -- app
        webservice -- app
        app -- domain
        domain -- repository
    }
}
interface REST
REST -- webservice
interface HTTP
HTTP -- adminui

@enduml
