@startuml
'https://plantuml.com/component-diagram

!include plantuml/Skin.iuml

package wbhonline.de {
    component WebBrowser {
        component HTML
        component JavaScript
        HTML - JavaScript
    }
    component CMS {
        component Joomla
        interface HTTP as "Web UI"
        Joomla -r- HTTP
        database MySQL
        interface SQL
        SQL - MySQL
        Joomla .d.> SQL
    }
    component Hoerbuchkatalog {
        component HBK {
            component RESTServer
            database Katalog
            RESTServer .d.> Katalog
            database Hoererdaten
            RESTServer .d.> Hoererdaten
        }
        interface REST
        RESTServer - REST
    }
    Joomla .r.> REST
    HTML .> HTTP
    JavaScript .u.> REST
}

@enduml
