@startuml

!include plantuml/Skinparams.iuml

component "Client mit\nClient Credentials Flow" as IDP_ClientCredentials <<ID Provider>> {
}
component "Client mit\nAuthorization Code Flow" as IDP_AuthorizationCode <<ID Provider>> {
}

component "Hoerbuchkatalog" as HBK {
    component webservice <<Adapter>> {
    }
    webservice -l- IDP_ClientCredentials
    component adminui <<Adapter>> {
    }
    adminui -r- IDP_AuthorizationCode
    rectangle Domain {
        component app <<Services>> {
        }
        component domain <<Domain>> {
        }
        component adapter <<module>> {
        }
        adminui -d- app
        webservice -d- app
        app -d- domain
        domain -d- adapter
        database "Katalog\nGesamt.dat" as Katalog
        database "Hoererdaten\nhoe*.dat\nbk*.dat" as Hoererdaten
        database Downloads <<JsonRepository>>
        adapter -d- Downloads
        adapter -r- Katalog
        adapter -l- Hoererdaten
    }
}
interface REST
REST -- webservice
interface HTTP
HTTP -- adminui

@enduml
