@startuml
'https://plantuml.com/component-diagram

!include plantuml/Skinparams.iuml

left to right direction

actor WBH
component "Web Browser" as WBH_WebBrowser
component "S3 Browser" as WBH_S3Browser

actor "Hörer:in" as Hoerer
component "Web Browser" as Hoerer_WebBrowser {
    component HTML
    component JavaScript
    HTML -l- JavaScript
}

package wbh-online.de {
    component "KeyCloak" as IDP <<ID Provider>>
    component "CMS" as CMS
    component "Hörbuchkatalog" as HBK
    component "Hörbuchdienst" as HBD
    CMS - HBK
}

Hoerer -d- Hoerer_WebBrowser
HTML --- CMS
HTML --- HBD

WBH -u- WBH_S3Browser
WBH_S3Browser -u- HBD
WBH -u- WBH_WebBrowser
WBH_WebBrowser -u- CMS
WBH_WebBrowser -u- HBK
WBH_WebBrowser -u- HBD

@enduml
