== Hörbuchdienst

=== Storage Server provisionieren

netcup Storage Server installieren:

* ArchLinux
* Ausführung "Minimal"
* Partitionen: "Das Betriebssystem wird in einer kleinen Partition bereit gestellt.
Der restliche Speicherplatz kann nach Bedarf partitioniert werden."

.Auf dem Client
Bitte `N` gegen die entsprechende Nummer ersetzen

[source,shell,linenum]
----
ssh-keygen -R shardN.audiobook.wbh-online.de
ssh-keygen -R <IP Adresse shardN>
ssh-keyscan shardN.audiobook.wbh-online.de 2>/dev/null >>~/.ssh/known_hosts
ssh-keygen -H
ssh-copy-id -i ~/.ssh/id_rsa root@shardN1.audiobook.wbh-online.de <1>
----
<1> Bei Aufforderung das Passwort aus der Konsole des Providers verwenden.

.shard1
[source,shell,linenum]
----
ssh-keygen -R shard1.audiobook.wbh-online.de
ssh-keygen -R 188.68.50.68
ssh-keyscan shard1.audiobook.wbh-online.de 2>/dev/null >>~/.ssh/known_hosts
ssh-copy-id -i ~/.ssh/id_rsa root@shard1.audiobook.wbh-online.de
----

.shard2
[source,shell,linenum]
----
ssh-keygen -R shard2.audiobook.wbh-online.de
ssh-keygen -R 188.68.43.25
ssh-keyscan shard2.audiobook.wbh-online.de 2>/dev/null >>~/.ssh/known_hosts
ssh-copy-id -i ~/.ssh/id_rsa root@shard2.audiobook.wbh-online.de
----

.Auf dem Shard einloggen:
[source,shell,linenum]
----
ssh root@shardN.audiobook.wbh-online.de
----

.SSH Schlüssel generieren
[source,shell,linenum]
----
ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
cat ~/.ssh/id_rsa.pub
----

und den Public Key auf GitHub und Bitbucket zum Zugriff durch den Server auf den Source Code hinterlegen lassen.

.WBH Bookworm auschecken
[source,shell,linenum]
----
ssh-keyscan github.com 2>/dev/null >>~/.ssh/known_hosts
ssh-keyscan bitbucket.org 2>/dev/null >>~/.ssh/known_hosts
git clone git@bitbucket.org:artofcoding/bookworm2 ~/bookworm2
cd ~/bookworm2
git config pull.rebase false
git checkout master
----

.Installation Teil 1 -- Die Installation starten:
[source,shell,linenum]
----
bookworm2 $ bash hoerbuchdienst/bin/setup-storageserver-1.sh
----

und bei Aufforderung Shard Name eingeben (shardN.audiobook.wbh-online.de) und mit der Eingabe 'yes' bestätigen:

[source,text,linenum]
----
Please enter FQDN of shard: shard2.audiobook.wbh-online.de
Shard name is shard2
Shard's domain is audiobook.wbh-online.de
Is this correct? (Enter 'yes') yes
----

Nach erfolgreicher Installation erfolgt automatisch ein Reboot.

.Installation Teil 2 -- Storage einrichten und Docker installieren:
[source,shell,linenum]
----
bookworm2 $ bash hoerbuchdienst/bin/setup-storageserver-2.sh
----

.Lokale Namensauflösung
Alle Shards müssen dem einzurichtenden Shard bekannt sein.

----
cat >/etc/hosts <<EOF
# Static table lookup for hostnames.
# See hosts(5) for details.
127.0.0.1       localhost
188.68.50.68    shard1.audiobook.wbh-online.de  rabbitmq.shard1.audiobook.wbh-online.de  shard1
188.68.43.25    shard2.audiobook.wbh-online.de  rabbitmq.shard2.audiobook.wbh-online.de  shard2
EOF
----

=== Applikationen verwalten

==== Installation

Die folgenden Schritte müssen auf einem Shard durchgeführt werden.

.Software für Produktion bauen
[source,shell,linenum]
----
bookworm2 $ ./build.sh prod
----

Der Release Zeitpunkt:

* kann aus den Logausgaben abgelesen werden,
* ist an den Artefakten im Verzeichnis `assembly/target/dependency` ableser oder kann
* alternativ mit `docker image ls` die aktuellsten Images nachschauen.

.Beispiel assembly/target/dependency
[source,shell,linenum]
----
bookworm2 $ ls -l assembly/target/dependency/
total 37940
-rw-r--r-- 1 root root    51279 Jul 18 11:03 wbh.bookworm.cms.assembly-2020-07-18T09-02-06Z.zip
-rw-r--r-- 1 root root    58689 Jul 18 11:08 wbh.bookworm.hoerbuchdienst.assembly-2020-07-18T09-02-06Z.zip
-rw-r--r-- 1 root root 38733860 Jul 18 11:04 wbh.bookworm.hoerbuchkatalog.deployment-2020-07-18T09-02-06Z.zip
----

Hier ist der Zeitstempel `2020-07-18T09-02-06Z`.

.Das Deployment durchführen
Dabei den gewünschten Release-Zeitpunkt wählen und per `deploy.sh` in das `release`-Verzeichnis einspielen lassen:

[source,shell,linenum]
----
bookworm2 $ ./deploy.sh prod hbd 2020-07-18T09-02-06Z
----

.Starten der Applikationen
In das erstellte Release-Verzeichnis wechseln:

[source,shell,linenum]
----
bookworm2 $ cd ~/releases/prod-hbd-2020-07-18T09-02-06Z/wbh.bookworm.hoerbuchdienst.assembly
releases/prod-hbd-2020-07-16T17-16-39Z/wbh.bookworm.hoerbuchdienst.assembly $ ./lifecycle.sh start
----

==== RabbitMQ

Die Einrichtung von RabbitMQ erfordert manuelle Schritte.
Dabei wird in der neuen RabbitMQ Instanz das Passwort für den Nutzer `federator` gesetzt und die weiteren, bereits eingerichteten RabbitMQ Instanzen können bekannt gemacht werden.

.RabbitMQ erstmalig provisionieren
[source,shell,linenum]
----
docker-compose -p prod-hbd exec rabbitmq rabbitmq-provision.sh
----

Beispiel:

[source,shell,linenum]
----
wbh.bookworm.hoerbuchdienst.assembly $ docker-compose -p prod-hbd exec rabbitmq rabbitmq-provision.sh
Checking if RabbitMQ is online
RabbitMQ appears to be online
Setting password for RabbitMQ federator
Generated RabbitMQ federator password: Abc123Def456
Changing password for user "federator" ...
done
----

.Andere RabbitMQ Instanzen anbinden
[source,shell,linenum]
----
docker-compose -p prod-hbd exec rabbitmq rabbitmq-setup-federation.sh \
    "rabbitmq.shard2:user:pwd" \ <1>
    "rabbitmq.shard3:user:pwd"   <2>
----
<1> Ein weiterer, bereits eingerichteter Shard `shard2`
<2> Ein weiterer, bereits eingerichteter Shard `shard3`

Nutzer ist dabei `federator`, das Passwort ist für jeden Shard eigens vergeben.

Auf Shard1

[source,shell,linenum]
----
docker-compose -p prod-hbd exec rabbitmq rabbitmq-setup-federation.sh "rabbitmq.shard2:federator:Abc123Def456"
----

[source,shell,linenum]
----
wbh.bookworm.hoerbuchdienst.assembly $ docker-compose -p prod-hbd exec rabbitmq rabbitmq-setup-federation.sh "rabbitmq.shard2:federator:Abc123Def456"
Checking if RabbitMQ is online
RabbitMQ appears to be online
My node name is rabbitmq.shard1.audiobook.wbh-online.de
Common domain for all shards is audiobook.wbh-online.de
Adding federation upstream to rabbitmq.shard2.audiobook.wbh-online.de at amqps://federator:vae9eiwie3Eikiec@rabbitmq.shard2.audiobook.wbh-online.de:5671/hoerbuchdienst
Setting runtime parameter "shard2" for component "federation-upstream" to "{"uri":"amqps://federator:Abc123Def456@rabbitmq.shard2.audiobook.wbh-online.de:5671/hoerbuchdienst?server_name_indication=rabbitmq.shard2.audiobook.wbh-online.de&heartbeat=10&connection_timeout=10000"}" in vhost "hoerbuchdienst" ...
----

Auf Shard2:

[source,shell,linenum]
----
docker-compose -p prod-hbd exec rabbitmq rabbitmq-setup-federation.sh "rabbitmq.shard1:federator:Abc123Def456"
----

Beispiel:

[source,shell,linenum]
----
wbh.bookworm.hoerbuchdienst.assembly $ docker-compose -p prod-hbd exec rabbitmq rabbitmq-setup-federation.sh "rabbitmq.shard1:federator:Abc123Def456"
Checking if RabbitMQ is online
RabbitMQ appears to be online
My node name is rabbitmq.shard2.audiobook.wbh-online.de
Common domain for all shards is audiobook.wbh-online.de
Adding federation upstream to rabbitmq.shard1.audiobook.wbh-online.de at amqps://federator:Abc123Def456@rabbitmq.shard1.audiobook.wbh-online.de:5671/hoerbuchdienst
Setting runtime parameter "shard1" for component "federation-upstream" to "{"uri":"amqps://federator:Aeh9eech3coo7tho@rabbitmq.shard1.audiobook.wbh-online.de:5671/hoerbuchdienst?server_name_indication=rabbitmq.shard1.audiobook.wbh-online.de&heartbeat=10&connection_timeout=10000"}" in vhost "hoerbuchdienst" ...
----

.Fehlerfall: sich selbst als Upstream einrichten geht nicht
Hier soll auf shard2 ein Upstream auf shard2 eingerichtet werden und wird mit der Meldung `Cannot add myself as upstream` abgelehnt:
[source,shell,linenum]

[source,shell,linenum]
----
shard2 $ docker-compose -p prod-hbd exec rabbitmq rabbitmq-setup-federation.sh "rabbitmq.shard2:federator:Abc123Def456"
Checking if RabbitMQ is online
RabbitMQ appears to be online
My node name is rabbitmq.shard2.audiobook.wbh-online.de
Common domain for all shards is audiobook.wbh-online.de
Cannot add myself as upstream
----

IMPORTANT: Die durch die Erstinstallation und den ersten Start erzeugten Volumes und Daten dürfen keinesfalls verändert oder gar gelöscht werden!

==== Aktualisierung

.Software erneut bauen
[source,shell,linenum]
----
cd ~/bookworm2
git fetch origin
git checkout origin/master -- autoupdate.sh
./autoupdate.sh prod hbd
----

.Stop
In das *zuvor genutzte Release-Verzeichnis* wechseln:

[source,shell,linenum]
----
bookworm2 $ cd ~/releases/prod-hbd-2020-07-16T17-16-39Z/wbh.bookworm.hoerbuchdienst.assembly
releases/prod-hbd-2020-07-16T17-16-39Z/wbh.bookworm.hoerbuchdienst.assembly $ ./lifecycle.sh stop
----

.Start
Die `restart.sh` mit Umgebung und Projekt aufrufen:

[source,shell,linenum]
----
$ restart.sh prod hbd
----

=== Backup

----
/var/lib/docker/volumes/prod-hbd_keslocal/_data/minio.cert
/var/lib/docker/volumes/prod-hbd_keslocal/_data/minio.key
/var/lib/docker/volumes/prod-hbd_keslocal/_data/root.cert
/var/lib/docker/volumes/prod-hbd_keslocal/_data/root.key
/var/lib/docker/volumes/prod-hbd_keslocal/_data/server-config.yml
----

----
echo "MinIO Access Key=$(cat /var/lib/docker/volumes/prod-hbd_miniolocal/_data/access_key)"
echo "MinIO Secret Key=$(cat /var/lib/docker/volumes/prod-hbd_miniolocal/_data/secret_key)"
echo "MinIO Admin Access Key=$(head -1 /var/lib/docker/volumes/prod-hbd_mclocal/_data/user_admin)"
echo "MinIO Admin Secret Key=$(tail -1 /var/lib/docker/volumes/prod-hbd_mclocal/_data/user_admin)"
echo "MinIO WBH Access Key=$(head -1 /var/lib/docker/volumes/prod-hbd_mclocal/_data/user_wbh)"
echo "MinIO WBH Secret Key=$(tail -1 /var/lib/docker/volumes/prod-hbd_mclocal/_data/user_wbh)"
----

----
cat /var/lib/docker/volumes/prod-hbd_vaultconfig/_data/vault-operator-init.txt
cat /var/lib/docker/volumes/prod-hbd_vaultconfig/_data/kes-role-id.json
cat /var/lib/docker/volumes/prod-hbd_vaultconfig/_data/kes-secret-id.json
----
