== Administration

=== Grundsätzliches

Alle Skripte nutzen das Home-Verzeichnis des Benutzers, der sie ausführt.

[cols="20%a,80%a",opts="header"]
|====
| Skript
| Beschreibung

| autoupdate.sh
|

| build.sh
|

| cleanup.sh
|

| cnt.sh
|

| deploy.sh
|

| release.sh
|

| restart.sh
|

| total-destroy.sh
|
|====

Folgende Verzeichnisse werden angelegt:

[cols="20%a,80%a",opts="header"]
|====
| Verzeichnis
| Beschreibung

| bookworm2
| WBH Bookworm Version 2: Hörbuchkatalog, Hörbuchdienst, Docker Container (auch für das CMS).

| mikrokosmos
| https://github.com/rbe/mikrokosmos[Mikrokosmos] stellt verschiedene technische Dienste bereit welche WBH Bookworm nutzt.

| releases
| Alle erzeugten Releases werden hier abgelegt.

| maven-repository
| Enthält das lokale Maven Repository, den Cache für Artefakte.
|====

=== Verwaltung der Container

Das Skript `cnt.sh` vereinfacht die Ausführung von Docker Compose-Kommandos des zuletzt erzeugten Releases.

[source,shell,linenum]
----
cnt.sh <environment> <project> exec <service> <Docker Compose command>
----

TIP: Einen Alias in der Shell anlegen: `alias prodhbd="cnt.sh prod hbd"`

.Beispiel Alle Dienste auflisten:
[source,shell,linenum]
----
cnt.sh prod hbd ps
----

Ausgabe:

[source,text,subs="quotes"]
----
Executing for version 2020-07-22T12-34-34Z
          Name                       Command             State  Ports
--------------------------------------------------------------------------------------------------------
prod-hbd_**hbd-rproxy**\_1     /usr/local/bin/docker-entr ... Up     0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
prod-hbd_**hoerbuchdienst**\_1 java -Dmicronaut.config.fi ... Up
prod-hbd_**kes**\_1            /usr/local/bin/docker-entr ... Up
prod-hbd_**mc**\_1             tail -f /dev/null              Up
prod-hbd_**minio**\_1          /usr/local/bin/docker-entr ... Up
prod-hbd_**portainer**\_1      /portainer                     Up
prod-hbd_**rabbitmq**\_1       /usr/local/bin/my-docker-e ... Up     0.0.0.0:5671->5671/tcp
prod-hbd_**vault**\_1          docker-entrypoint.sh /bin/ ... Up
prod-hbd_**virenscanner**_1   /usr/local/bin/docker-entr ... Up     3310/tcp
----

Die _Services_ sind hier fett markiert.
Services können ohne ihren Prefix `prod-hbd` und Suffix `_1` bei Docker Compose-Kommandos angegeben werden.

.Beispiel Den Hörbuchdienst neu starten:
[source,shell,linenum]
----
cnt.sh prod hbd restart hoerbuchdienst
----

Während eines Neustarts wird im Log angezeigt, dass der Shard nicht mehr aktiv ist und dann wieder zurückkehrt:

[source,shell,linenum,subs="verbatim,quotes"]
----
14:12:52.978 ERROR w.b.h.a.r.d.a.HeartbeatMessageReceiver - *Current number of heartbeats (1)* within 5 secs *lower than high water mark (2)*
14:12:52.978 ERROR w.b.h.a.r.d.a.HeartbeatMessageReceiver - *Shard hoerbuchdienst.shard1.audiobook.wbh-online.de disappeared!* <1>
14:12:52.978 INFO  w.b.h.a.r.d.a.DataHeartbeatMessageReceiver - *Removed hoerbuchdienst.shard1.audiobook.wbh-online.de's data from cache as it disappeared*
14:13:22.537 INFO  w.b.h.a.r.d.a.HeartbeatMessageReceiver - *Welcome back, shard hoerbuchdienst.shard1.audiobook.wbh-online.de!* <2>
----
<1> Shard ist nicht mehr aktiv
<2> Shard kehr wieder zurück

.Beispiel Logs dauerhaft des Reverse Proxy anschauen:
[source,shell,linenum]
----
cnt.sh prod hbd logs -f hbd-rproxy
----
Abbruch mit Strg-C.

.Beispiel Shell im Reverse Proxy öffnen:
[source,shell,linenum]
----
cnt.sh prod hbd exec hbd-rproxy ash
----

.Beispiel Konfiguration Reverse Proxy neu laden:
[source,shell,linenum]
----
cnt.sh prod hbd exec hbd-rproxy nginx -s reload
----
