== Inbetriebnahme

=== Storage Server provisionieren

==== Server installieren

IONOS Storage Server:

* openSUSE Leap 15.1

netcup Storage Server installieren:

* ArchLinux
* Ausführung "Minimal"
* Partitionen: "Das Betriebssystem wird in einer kleinen Partition bereit gestellt.
Der restliche Speicherplatz kann nach Bedarf partitioniert werden."

==== SSH Zugriff einrichten

.Auf dem Client
Der Administrator muss seinen SSH-Schlüssel für den Login auf dem Shard hinterlegen.
Bitte `N` gegen die entsprechende Nummer ersetzen:

.Linux, macOS
[source,shell,linenum]
----
ssh-keygen -R shardN.wbh-online.de
ssh-keygen -R <IP Adresse shardN>
ssh-keyscan shardN.wbh-online.de 2>/dev/null >>~/.ssh/known_hosts
ssh-keygen -H
ssh-copy-id -i ~/.ssh/id_rsa root@shardN.wbh-online.de <1>
----
<1> Bei Aufforderung das Passwort aus der Konsole des Providers verwenden.

.shard1.wbh-online.de
[source,shell,linenum]
----
ssh-keygen -R shard1.wbh-online.de
ssh-keygen -R 188.68.50.68
ssh-keyscan shard1.wbh-online.de 2>/dev/null >>~/.ssh/known_hosts
ssh-copy-id -i ~/.ssh/id_rsa root@shard1.wbh-online.de
----

.shard2.wbh-online.de
[source,shell,linenum]
----
ssh-keygen -R shard2.wbh-online.de
ssh-keygen -R 188.68.43.25
ssh-keyscan shard2.wbh-online.de 2>/dev/null >>~/.ssh/known_hosts
ssh-copy-id -i ~/.ssh/id_rsa root@shard2.wbh-online.de
----

==== Linux aktualisieren

.Linux aktualisieren
----
# ArchLinux
pacman --noconfirm -Syu git
# CentOS
yum -y update
yum -y install git
# openSUSE
zypper update -y
zypper install -y git
----

==== Das Projekt klonen

.Auf dem Shard einloggen:
[source,shell,linenum]
----
ssh root@shardN.wbh-online.de
----

.SSH Schlüssel generieren
Damit der Source Code auf dem Shard heruntergeladen werden kann, muss ein SSH Schlüssel erzeugt werden.

[source,shell,linenum]
----
ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N "" -C "wbh-shardN"
cat ~/.ssh/id_rsa.pub
----

und der Public Key muss auf GitHub und Bitbucket zum Zugriff durch den Shard hinterlegt werden.

.Source Code auschecken
[source,shell,linenum]
----
git config --global pull.rebase false
ssh-keyscan github.com 2>/dev/null >>~/.ssh/known_hosts
ssh-keyscan bitbucket.org 2>/dev/null >>~/.ssh/known_hosts
git clone git@bitbucket.org:artofcoding/bookworm2 ~/bookworm2
----

.Update Bookworm2
----
cd ~/bookworm2 && git pull && cd -
----

==== Erstinstallation durchführen

.Installation Teil 1 -- Die Installation starten:
[source,shell,linenum]
----
bash ~/bookworm2/hoerbuchdienst/bin/ionos/openSUSE/setup-shard-1.sh
----

und bei Aufforderung Shard Name eingeben (shardN.wbh-online.de) und mit der Eingabe 'yes' bestätigen:

[source,text,linenum]
----
Please enter FQDN of shard: shard1.wbh-online.de
Shard name is shard1
Shard's domain is wbh-online.de
Is this correct? (Enter 'yes') yes
----

WARNING: Die eingegebenen Informationen müssen korrekt sein!
Erfolgt keine Bestätigung per Eingabe von 'yes' wird die Abfrage wiederholt.

Nach erfolgreicher Installation erfolgt automatisch ein Reboot.

.Installation Teil 2 -- Storage einrichten und Docker installieren:
[source,shell,linenum]
----
bash ~/bookworm2/hoerbuchdienst/bin/ionos/openSUSE/setup-shard-2.sh
----

==== Netzwerkkonfiguration

.Namensauflösung
Alle bereits existierenden Shards müssen dem einzurichtenden Shard bekannt sein.
Dies kann a) per DNS und/oder b) durch lokale Dienste wie `/etc/hosts` erfolgen.

WARNING: Die *zwingend* zu konfigurierenden Namen sind wie folgt, dabei ist die Domäne immer `wbh-online.de`:

[cols="45%a,55%a",opts="header",subs="quotes"]
|====
| Name
| Beschreibung

| shard__N__.wbh-online.de
| Der Shard/der Server selbst

| vault-shard__N__.wbh-online.de
| Vault

| kes-shard__N__.wbh-online.de
| MinIO KES

| s3-shard__N__.wbh-online.de
| MinIO

| rabbitmq-shard__N__.wbh-online.de
| RabbitMQ

| hoerbuchdienst-shard__N__.wbh-online.de
| Hörbuchdienst
|====

.Lokale Namensauflösung per /etc/hosts einrichten
[source,shell,linenum]
----
$ cat >/etc/hosts <<EOF
# Static table lookup for hostnames.
# See hosts(5) for details.
127.0.0.1       localhost
188.68.50.68    shard1.wbh-online.de  rabbitmq.shard1.wbh-online.de  shard1
188.68.43.25    shard2.wbh-online.de  rabbitmq.shard2.wbh-online.de  shard2
... <1>
EOF
----
<1> Ggf. weitere Shards

=== Hörbuchdienst installieren

IMPORTANT: Die durch die Erstinstallation und den ersten Start erzeugten Volumes und Daten dürfen keinesfalls verändert oder gar gelöscht werden!

Die folgenden Schritte müssen auf einem Shard durchgeführt werden.

.Software für Produktion bauen, deployen und starten
[source,shell,linenum]
----
~/bookworm2/autoupdate.sh prod hbd force
----

.Releases
Der durch das Bauen erzeugte Release Zeitpunkt:

* kann aus den Logausgaben des Builds abgelesen werden,
* ist an den Artefakten im Verzeichnis `assembly/target/dependency` ablesbar oder
* kann per `docker image ls` (die jeweils aktuellsten Images) nachgesehen werden.

.Beispiel assembly/target/dependency
[source,shell,linenum]
----
bookworm2 $ ls -l assembly/target/dependency/
total 37940
-rw-r--r-- 1 root root    51279 Jul 18 11:03 wbh.bookworm.cms.assembly-2020-07-18T09-02-06Z.zip
-rw-r--r-- 1 root root    58689 Jul 18 11:08 wbh.bookworm.hoerbuchdienst.assembly-2020-07-18T09-02-06Z.zip
-rw-r--r-- 1 root root 38733860 Jul 18 11:04 wbh.bookworm.hoerbuchkatalog.deployment-2020-07-18T09-02-06Z.zip
----

Hier ist der Zeitstempel `2020-07-18T09-02-06Z`.

.Das Deployment durchführen
Dabei den gewünschten Release-Zeitpunkt wählen und per `deploy.sh` in das `release`-Verzeichnis einspielen lassen:

[source,shell,linenum]
----
~/bookworm2/deploy.sh prod hbd 2020-07-18T09-02-06Z
----

.Starten der Applikationen
In das erstellte Release-Verzeichnis wechseln:

[source,shell,linenum]
----
$ cd ~/releases/prod-hbd-2020-07-18T09-02-06Z/wbh.bookworm.hoerbuchdienst.assembly
releases/prod-hbd-2020-07-16T17-16-39Z/wbh.bookworm.hoerbuchdienst.assembly $ ./lifecycle.sh start
----

==== Message Queue einrichten

Die Einrichtung von RabbitMQ erfordert manuelle Schritte durch die alle Shards miteinander bekannt gemacht werden.
Dabei wird in der neuen RabbitMQ Instanz das Passwort für den Nutzer `federator` gesetzt und die weiteren, bereits eingerichteten RabbitMQ Instanzen können verbunden werden.

.RabbitMQ erstmalig provisionieren
[source,shell,linenum]
----
cnt.sh prod hbd exec rabbitmq rabbitmq-provision.sh
----

Ausgabe:

[source,shell,linenum]
----
Checking if RabbitMQ is online
RabbitMQ appears to be online
Setting password for RabbitMQ federator
Generated RabbitMQ federator password: Abc123Def456
Changing password for user "federator" ...
done
Checking if RabbitMQ is online
RabbitMQ appears to be online
Adding user "exporteur-yae3beeb" ...
Changing password for user "exporteur-yae3beeb" ...
Setting tags for user "exporteur-yae3beeb" to [administrator] ...
Setting permissions for user "exporteur-yae3beeb" in vhost "hoerbuchdienst" ...
Exporting RabbitMQ definitions
Exported definitions for rabbitmq.s22587203.onlinehome-server.info to "/etc/rabbitmq/definitions.json"
done
Deleting user "exporteur-yae3beeb" ...
----

.Andere RabbitMQ Instanzen anbinden
[source,shell,linenum,subs="verbatim"]
----
cnt.sh prod hbd exec rabbitmq rabbitmq-setup-federation.sh \
  "*rabbitmq.shard2*:user:pwd" \ <1>
  "*rabbitmq.shard3*:user:pwd"   <2>
----
<1> Ein weiterer, bereits eingerichteter Shard `shard2`
<2> Ein weiterer, bereits eingerichteter Shard `shard3`

Nutzer ist dabei `federator`, das Passwort ist für jeden Shard eigens vergeben.

Auf Shard1

[source,shell,linenum]
----
cnt.sh prod hbd exec rabbitmq rabbitmq-setup-federation.sh "rabbitmq.shard2:federator:Abc123Def456"
----

Ausgabe:

[source,shell,linenum,subs="quotes"]
----
Checking if RabbitMQ is online
RabbitMQ appears to be online
My node name is rabbitmq.shard1.wbh-online.de
Common domain for all shards is wbh-online.de
Adding federation upstream to *rabbitmq.shard2*.wbh-online.de at amqps://federator:Abc123Def456@rabbitmq.shard2.wbh-online.de:5671/hoerbuchdienst
Setting runtime parameter "shard2" for component "federation-upstream" to "{"uri":"amqps://federator:Abc123Def456@rabbitmq.shard2.wbh-online.de:5671/hoerbuchdienst?server_name_indication=rabbitmq.shard2.wbh-online.de&heartbeat=10&connection_timeout=10000"}" in vhost "hoerbuchdienst" ...
----

Auf Shard2:

[source,shell,linenum]
----
cnt.sh prod hbd exec rabbitmq rabbitmq-setup-federation.sh "rabbitmq.shard1:federator:Abc123Def456"
----

Ausgabe:

[source,shell,linenum,subs="quotes"]
----
Checking if RabbitMQ is online
RabbitMQ appears to be online
My node name is rabbitmq.shard2.audiobook.wbh-online.de
Common domain for all shards is audiobook.wbh-online.de
Adding federation upstream to *rabbitmq.shard1*.audiobook.wbh-online.de at amqps://federator:Abc123Def456@rabbitmq.shard1.audiobook.wbh-online.de:5671/hoerbuchdienst
Setting runtime parameter "shard1" for component "federation-upstream" to "{"uri":"amqps://federator:Abc123Def456@rabbitmq.shard1.audiobook.wbh-online.de:5671/hoerbuchdienst?server_name_indication=rabbitmq.shard1.audiobook.wbh-online.de&heartbeat=10&connection_timeout=10000"}" in vhost "hoerbuchdienst" ...
----

.Fehlerfall: sich selbst als Upstream einrichten geht nicht
Hier soll auf shard2 ein Upstream auf shard2 eingerichtet werden und wird mit der Meldung `Cannot add myself as upstream` abgelehnt:

[source,shell,subs="quotes"]
----
*shard2* $ cnt.sh prod hbd exec rabbitmq rabbitmq-setup-federation.sh "*rabbitmq.shard2*:federator:Abc123Def456"
----

Ausgabe:

[source,shell,linenum,subs="quotes"]
----
Checking if RabbitMQ is online
RabbitMQ appears to be online
My node name is *rabbitmq.shard2*.audiobook.wbh-online.de
Common domain for all shards is audiobook.wbh-online.de
*Cannot add myself as upstream*
----

.Federated Exchange und Queue einrichten
[source,shell,linenum]
----
$ cnt.sh prod hbd exec rabbitmq rabbitmq-add-federated-exchange.sh \
    federator:<password> databeat fanout databeat true
----

.TTL für Nachrichten auf einer Queue setzen
[source,shell,linenum]
----
$ cnt.sh prod hbd exec rabbitmq rabbitmq-set-queue-message-ttl.sh \
    databeat-message-ttl "^databeat$" 30000
----

NOTE: Die Konfiguration der TTL für Nachrichten ist bereits in der `definitions.json` enthalten und wird somit automatisch gesetzt.

.Nutzer für den Hörbuchdienst einrichten
----
$ cnt.sh prod hbd exec rabbitmq rabbitmq-change-password.sh bugs
----

==== Weitere Inbetriebnahme

----
rm /var/lib/docker/volumes/prod-hbd_rproxycerts/_data/is_initialized
cnt.sh prod hbd exec hbd-rproxy provision.sh default_tls_server
cnt.sh prod hbd restart hbd-rproxy
----

----
cnt.sh prod hbd exec hbd-rproxy provision.sh default_tls_server minio rabbitmq
----

----
cnt.sh prod hbd exec hbd-rproxy provision.sh hoerbuchdienst
----

==== Aktualisierung

.Software erneut bauen
[source,shell,linenum]
----
cd ~/bookworm2
git fetch origin
git checkout origin/master -- autoupdate.sh
./autoupdate.sh prod hbd
----

TIP: Shell Alias `update-hbd` benutzen.

=== Backup

----
/var/lib/docker/volumes/prod-hbd_keslocal/_data/minio.cert
/var/lib/docker/volumes/prod-hbd_keslocal/_data/minio.key
/var/lib/docker/volumes/prod-hbd_keslocal/_data/root.cert
/var/lib/docker/volumes/prod-hbd_keslocal/_data/root.key
/var/lib/docker/volumes/prod-hbd_keslocal/_data/server-config.yml
----

----
echo "MinIO Access Key=$(cat /var/lib/docker/volumes/prod-hbd_miniolocal/_data/access_key)"
echo "MinIO Secret Key=$(cat /var/lib/docker/volumes/prod-hbd_miniolocal/_data/secret_key)"
echo "MinIO Admin Access Key=$(head -1 /var/lib/docker/volumes/prod-hbd_mclocal/_data/user_admin)"
echo "MinIO Admin Secret Key=$(tail -1 /var/lib/docker/volumes/prod-hbd_mclocal/_data/user_admin)"
echo "MinIO WBH Access Key=$(head -1 /var/lib/docker/volumes/prod-hbd_mclocal/_data/user_wbh)"
echo "MinIO WBH Secret Key=$(tail -1 /var/lib/docker/volumes/prod-hbd_mclocal/_data/user_wbh)"
----

----
cat /var/lib/docker/volumes/prod-hbd_vaultconfig/_data/vault-operator-init.txt
cat /var/lib/docker/volumes/prod-hbd_vaultconfig/_data/kes-role-id.json
cat /var/lib/docker/volumes/prod-hbd_vaultconfig/_data/kes-secret-id.json
----
