[[section-glossary]]
== Glossar

[role="arc42help"]
****
.Inhalt
Die wesentlichen fachlichen und technischen Begriffe, die Stakeholder im Zusammenhang mit dem System verwenden.

Nutzen Sie das Glossar ebenfalls als Übersetzungsreferenz, falls Sie in mehrsprachigen Teams arbeiten.

.Motivation
Sie sollten relevante Begriffe klar definieren, so dass alle Beteiligten

1. diese Begriffe identisch verstehen, und
2. vermeiden, mehrere Begriffe für die gleiche Sache zu haben.


.Form
* Zweispaltige Tabelle mit <Begriff> und <Definition>
* Eventuell weitere Spalten mit Übersetzungen, falls notwendig.
****

[cols="1,2" options="header"]
|===
|Begriff
|Definition

|_<Begriff-1>_
|_<Definition-1>_


|_<Begriff-2_
|_<Definition-2>_
|===

Analysis Model	Angemeldeter Hörer
Analysis Model	blista
Analysis Model	Bookworm			Das System.
Analysis Model	CD
Analysis Model	Download
Analysis Model	Gesamt.dat
Analysis Model	Hörbuch	Hörbüchern, Hörbücher
Analysis Model	Hörbuchkatalog
Analysis Model	Hörer	Hörern, Hörers
Analysis Model	Hörerdaten
Analysis Model	iso.txt
Analysis Model	Katalogverwalter
Analysis Model	Kundenverwalter
Analysis Model	Merkliste
Analysis Model	Personendaten
Analysis Model	Stammdaten
Analysis Model	Unbekannter Hörer
Analysis Model	Warenkorb
